name: Elixir Test Suite

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      

jobs:
  test:
    runs-on: ubuntu22

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.10'
          otp-version: '22'

      - name: Install dependencies
        run: mix deps.get

      - name: Compile the project
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test --trace
